# Generated by Django 6.0 on 2025-12-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_cartitem_unique_together_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='category',
        ),
    ]
