# Generated by Django 6.0 on 2025-12-23 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_rename_user_review_customer_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
