# Generated by Django 6.0 on 2025-12-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_customerquery_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquery',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerquery',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='customerquery',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='customerquery',
            name='response',
        ),
        migrations.AddField(
            model_name='customerquery',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
    ]
